name: CI pipeline

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build container
        run: docker build . --tag champagne_coding:latest

      - name: Check contents of container
        run: docker run champagne_coding:latest ls -la

#      - name: Push container
#        run: |
#          echo $GH_PW | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin 
#          docker tag champagne_coding:latest $GH_REG/$GITHUB_REPOSITORY/champagne_coding:latest
#          docker push $GH_REG/$GITHUB_REPOSITORY/champagne_coding:latest
#        env:
#          GH_REG: docker.pkg.github.com
#          GH_PW: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to OpenShift
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: 'latest'
          openshift_server_url: paas.redpill-linpro.com
          parameters: '{ "username": "${{ secrets.EMAIL }}", "password": "${{ secrets.PASSWORD }}"}'
          run: |            
            docker tag champagne_coding:latest docker-registry-default.apps.redpill-linpro.com/champagne-coding/champ
            docker login -u default -p $(oc whoami -t) docker-registry-default.apps.redpill-linpro.com
            docker push docker-registry-default.apps.redpill-linpro.com/champagne-coding/champ
